# Use root/example as user/password credentials
version: '3.1'

services:

  nodeapp:
    image: syahmiahmad/cognixus-nodeapp
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      PORT: 3000
